# 1. Examen


## Nombre y Apellidos:  Sergio García Ruiz

In [ ]:
import pandas as pd
import numpy as np

# Dataset USA Population

**Carga el csv de la población de Estados Unidos, y obtén la siguiente información:**

In [ ]:
population = pd.read_csv('datasets/usa_states_population.csv') # Leer el dataset usa_states_population.csv
population.head()

Rank       State Postal  Population
0     1     Alabama     AL   4849377.0
1     2      Alaska     AK    736732.0
2     3     Arizona     AZ   6731484.0
3     4    Arkansas     AR   2966369.0
4     5  California     CA  38802500.0

### 1. Imprime los cinco estados más poblados de Estados Unidos

In [ ]:
population.sort_values(ascending=False, by = "Population")['State'].head(5) # Ordenar por 'population' y sacar los 5 primeros estados

4     California
44         Texas
9        Florida
32      New York
13      Illinois
Name: State, dtype: object

### 2. Imprime los cinco estados menos poblados de Estados Unidos

In [ ]:
population.sort_values(ascending=True, by = "Population")['State'].head(5) # Ordenar por 'population' y sacar los 5 primeros estado

51                 Wyoming
46                 Vermont
8     District of Columbia
1                   Alaska
34            North Dakota
Name: State, dtype: object

### 3. Imprime los estados de Estados Unidos que tengan menos de un millón de habitantes

In [ ]:
populationM = population[population['Population'] > 1000000] # Crear una mascara para 'population' mayor de 1000000
populationM

Rank           State Postal  Population
0      1         Alabama     AL   4849377.0
2      3         Arizona     AZ   6731484.0
3      4        Arkansas     AR   2966369.0
4      5      California     CA  38802500.0
5      6        Colorado     CO   5355866.0
6      7     Connecticut     CT   3596677.0
9     10         Florida     FL  19893297.0
10    11         Georgia     GA  10097343.0
11    12          Hawaii     HI   1419561.0
12    13           Idaho     ID   1634464.0
13    14        Illinois     IL  12880580.0
14    15         Indiana     IN   6596855.0
15    16            Iowa     IA   3107126.0
16    17          Kansas     KS   2904021.0
17    18        Kentucky     KY   4413457.0
18    19       Louisiana     LA   4649676.0
19    20           Maine     ME   1330089.0
20    21        Maryland     MD   5976407.0
21    22   Massachusetts     MA   6745408.0
22    23        Michigan     MI   9909877.0
23    24       Minnesota     MN   5457173.0
24    25     Mississippi     MS   2994079.0
25    26        Missouri     MO   6063589.0
26    27         Montana     MT   1023579.0
27    28        Nebraska     NE   1881503.0
28    29          Nevada     NV   2839098.0
29    30   New Hampshire     NH   1326813.0
30    31      New Jersey     NJ   8938175.0
31    32      New Mexico     NM   2085572.0
32    33        New York     NY  19746227.0
33    34  North Carolina     NC   9943964.0
35    36            Ohio     OH  11594163.0
36    37        Oklahoma     OK   3878051.0
37    38          Oregon     OR   3970239.0
38    39    Pennsylvania     PA  12787209.0
39    40     Puerto Rico     PR   3548397.0
40    41    Rhode Island     RI   1055173.0
41    42  South Carolina     SC   4832482.0
43    44       Tennessee     TN   6549352.0
44    45           Texas     TX  26956958.0
45    46            Utah     UT   2942902.0
47    48        Virginia     VA   8326289.0
48    49      Washington     WA   7061530.0
49    50   West Virginia     WV   1850326.0
50    51       Wisconsin     WI   5757564.0

**Comentario:** se pedía mostrar los estados con menos de un millón de habitantes, y estás mostrando los que tienen más de uno. El error está en la desigualdad, pero al printear los resultados se ve claramente que no es lo que se está pidiendo.

# Dataset Medals

**Carga el dataset de las medallas olímpicas y obtén la siguiente información:**

In [ ]:
medals = pd.read_csv('datasets/Medals.csv', delimiter = ";", encoding = "unicode_escape") # Leer el dataset uMedals.csv separando por ';'
medals.head(10)

Athlete   Age  Year Closing Ceremony Date  Gold Medals  \
0    Michael Phelps  23.0  2008            08/24/2008            8   
1    Michael Phelps  19.0  2004            08/29/2004            6   
2    Michael Phelps  27.0  2012            08/12/2012            4   
3  Natalie Coughlin  25.0  2008            08/24/2008            1   
4     Aleksey Nemov  24.0  2000            10/01/2000            2   
5     Alicia Coutts  24.0  2012            08/12/2012            1   
6    Missy Franklin  17.0  2012            08/12/2012            4   
7       Ryan Lochte  27.0  2012            08/12/2012            2   
8   Allison Schmitt  22.0  2012            08/12/2012            3   
9  Natalie Coughlin  21.0  2004            08/29/2004            2   

   Silver Medals  Bronze Medals  
0              0              0  
1              0              2  
2              2              0  
3              2              3  
4              1              3  
5              3              1  
6              0              1  
7              2              1  
8              1              1  
9              2              1

### 4. ¿Quién es el atleta con más MEDALLAS DE ORO y cuántas tiene? 

In [ ]:
medals.sort_values(ascending=False, by = "Gold Medals")['Athlete'].head(1) # Ordenar por 'Gold Medals' y sacar el primer valor

0    Michael Phelps
Name: Athlete, dtype: object

**Comentario:** está bien, pero te falta imprimir el número de medallas de oro que tiene.

### 5. ¿Quién es el atleta con más medallas EN TOTAL y cuántas tiene?

In [ ]:
medals['total_medals'] = medals['Gold Medals'] + medals['Silver Medals'] + medals['Bronze Medals'] #Sumar todas las medallas

In [ ]:
medals.groupby(['Athlete'], sort=False)['total_medals'].max().head(1) # Argupar por 'Athlete' porque salen varias veces y sacar el que tiene más medallas

Athlete
Michael Phelps    8
Name: total_medals, dtype: int64

**Comentario:** el resultado es Michael Phelps, pero ojo pide medallas en total, que son 22. Esto es porque tras agrupar, estás quedándote con el valor máximo en lugar de la suma de todos ellos.

### 6. ¿Quiénes fueron los TRES atletas que más medallas obtuvieron en 2002?

In [ ]:
medals2002 = medals[medals["Closing Ceremony Date"].str.contains("2002")] # Crear una máscara para las ceremonias de 2002
medals2002

Athlete   Age  Year Closing Ceremony Date  Gold Medals  \
34    Ole Einar Bjørndalen  28.0  2002            02/24/2002            4   
35         Janica Kostelic  20.0  2002            02/24/2002            3   
93             Marc Gagnon  26.0  2002            02/24/2002            2   
94           Yang Yang (A)  25.0  2002            02/24/2002            2   
99       Jochem Uytdehaage  25.0  2002            02/24/2002            2   
...                    ...   ...   ...                   ...          ...   
8541       Laure Pequegnot  26.0  2002            02/24/2002            0   
8542          Karen Putzer  23.0  2002            02/24/2002            0   
8543    Andreas Schifferer  27.0  2002            02/24/2002            0   
8544          Fritz Strobl  29.0  2002            02/24/2002            1   
8545     Jean-Pierre Vidal  24.0  2002            02/24/2002            1   

      Silver Medals  Bronze Medals  total_medals  
34                0              0             4  
35                1              0             4  
93                0              1             3  
94                1              0             3  
99                1              0             3  
...             ...            ...           ...  
8541              1              0             1  
8542              0              1             1  
8543              0              1             1  
8544              0              0             1  
8545              0              0             1  

[407 rows x 8 columns]

In [ ]:
medals2002.groupby(['Athlete'], sort=False)['total_medals'].max().head(3) # Argupar por 'Athlete' porque salen varias veces y sacar los 3 que tienen más medallas

Athlete
Ole Einar Bjørndalen    4
Janica Kostelic         4
Marc Gagnon             3
Name: total_medals, dtype: int64

# Pandas & Numpy

### 7. Dados dos df, imprimir aquellos empleados que ganan más que la media de su sector

In [ ]:
empleados = pd.DataFrame([["Maria",20,25000,'DevOps'],["Mario",25, 30000,'Inteligencia Artificial'],
                          ["Luisa",21,24000,'DevOps'],["Luis",25, 40000,'Inteligencia Artificial'],
                          ["Pepa",27,31000, 'Cyber Seguridad'],["Pepe",30, 18000, 'Big Data']], 
                         
                         columns=["Nombre","Edad","Salario", "Especialidad"])

salario_medio = pd.DataFrame([["DevOps",40000],["Inteligencia Artificial",35000],
                              ["Cyber Seguridad",30000],["Big Data",25000]], 
                             
                         columns=["Especialidad","Salario medio"])

In [ ]:
dataset = pd.merge(empleados, salario_medio, on='Especialidad', how='inner') # Hacer un merge por la columna Especialidad de tipo inner porque solo nos interesan las que coinciden
dataset

Nombre  Edad  Salario             Especialidad  Salario medio
0  Maria    20    25000                   DevOps          40000
1  Luisa    21    24000                   DevOps          40000
2  Mario    25    30000  Inteligencia Artificial          35000
3   Luis    25    40000  Inteligencia Artificial          35000
4   Pepa    27    31000          Cyber Seguridad          30000
5   Pepe    30    18000                 Big Data          25000

In [ ]:
datasetS= dataset[dataset['Salario'] > dataset['Salario medio']] # Crear una mascara para los salarios mayores a los salarios medios
datasetS

Nombre  Edad  Salario             Especialidad  Salario medio
3   Luis    25    40000  Inteligencia Artificial          35000
4   Pepa    27    31000          Cyber Seguridad          30000

### 8. Dada la matriz A calcula por fila y columna: suma, media, máximo y mínimo

In [ ]:
A = np.arange(1,17).reshape(4,4)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
#Por Fila
sum = np.sum(A, axis=1) # Sacar la suma de los valores de cada fila
print('Suma')
print(sum)

mean = np.mean(A, axis=1) # Sacar la media de los valores de cada fila
print('Media')
print(mean)

maximo = np.max(A, axis = 1) # Sacar el máximo de los valores de cada fila
print('Maximo')
print(maximo)

minimo = np.min(A, axis = 1) # Sacar el mínimo de los valores de cada fila
print('Minimo')
print(minimo)

Suma
[10 26 42 58]
Media
[ 2.5  6.5 10.5 14.5]
Maximo
[ 4  8 12 16]
Minimo
[ 1  5  9 13]


In [ ]:
#Por Columna
sum = np.sum(A, axis=0) # Sacar la suma de los valores de cada columna
print('Suma')
print(sum)

mean = np.mean(A, axis=0) # Sacar la media de los valores de cada columna
print('Media')
print(mean)

maximo = np.max(A, axis = 0) # Sacar el máximo de los valores de cada columna
print('Maximo')
print(maximo)

minimo = np.min(A, axis = 0) # Sacar el mínimo de los valores de cada columna
print('Minimo')
print(minimo)

Suma
[28 32 36 40]
Media
[ 7.  8.  9. 10.]
Maximo
[13 14 15 16]
Minimo
[1 2 3 4]


**Comentario:** el ejercicio está bien, pero para tener la puntuación completa, lo ideal sería haberlo hecho con una función.